name: WirelessRedstone
version: '${project.version}'
main: me.zatozalez.wirelessredstone.WirelessRedstone
api-version: 1.16
authors: [ ZatoZalez ]
description: Plugin for Wireless Redstone.
website: https://discord.gg/TsRTa7BUWm

commands:
  device:
    usage: "/device <info/give/link>"
    description: "View, give or manage Redstone Devices."
  wirelessredstone:
    aliases: "wr"
    usage: "/wirelessredstone <reload/disable>"
    description: "Manage the WirelessRedstone plugin."