name: WirelessRedstone
version: '${project.version}'
main: me.zatozalez.wirelessredstone.WirelessRedstone
api-version: 1.14
authors: [ ZatoZalez ]
commands:
  debug:
    usage: "/debug"
    description: "DEBUG: Get devices."
  givedevice:
    usage: "/givedevice"
    description: "Give devices to players."
  cancellink:
    usage: "/cancellink"
    description: "Cancel any ongoing link."
