name: WirelessRedstone
version: '${project.version}'
main: me.zatozalez.wirelessredstone.WirelessRedstone
api-version: 1.18
authors: [ ZatoZalez ]
commands:
  givedevice:
    usage: "/givedevice <player> <devicetype> <amount>"
    description: "Give devices to yourself or others."
  cancellink:
    usage: "/cancellink"
    description: "Cancel any on-going linking."
